import type { DataFieldMap } from "./types";

export const ppiFields = {
    interactor_a: {
        label: 'Interactor A',
        field: 'interactor_a',
        hidden: false,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    gene_a: {
        label: 'Gene A',
        field: 'gene_a',
        hidden: false,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    interactor_desc_a: {
        label: 'Desc A',
        field: 'interactor_desc_a',
        hidden: false,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    genome_name_a: {
        label: 'Genome Name A',
        field: 'genome_name_a',
        hidden: true,
        group: 'Interactor A',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    genome_id_a: {
        label: 'Genome ID A',
        field: 'genome_id_a',
        hidden: true,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: false,
    },
    feature_id_a: {
        label: 'Feature ID A',
        field: 'feature_id_a',
        hidden: true,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: false,
    },
    refseq_locus_tag_a: {
        label: 'RefSeq Locus Tag A',
        field: 'refseq_locus_tag_a',
        hidden: true,
        group: 'Interactor A',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    interactor_b: {
        label: 'Interactor B',
        field: 'interactor_b',
        hidden: false,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    gene_b: {
        label: 'Gene B',
        field: 'gene_b',
        hidden: false,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    interactor_desc_b: {
        label: 'Desc B',
        field: 'interactor_desc_b',
        hidden: false,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    genome_name_b: {
        label: 'Genome Name B',
        field: 'genome_name_b',
        hidden: true,
        group: 'Interactor B',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    genome_id_b: {
        label: 'Genome ID B',
        field: 'genome_id_b',
        hidden: true,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: false,
    },
    feature_id_b: {
        label: 'Feature ID B',
        field: 'feature_id_b',
        hidden: true,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: false,
    },
    refseq_locus_tag_b: {
        label: 'RefSeq Locus Tag B',
        field: 'refseq_locus_tag_b',
        hidden: true,
        group: 'Interactor B',
        facet: false,
        facet_hidden: true,
        search: true,
    },
    category: {
        label: 'Category',
        field: 'category',
        hidden: false,
        group: 'Interaction Details',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    interaction_type: {
        label: 'Interaction Type',
        field: 'interaction_type',
        hidden: false,
        group: 'Interaction Details',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    detection_method: {
        label: 'Detection Method',
        field: 'detection_method',
        hidden: false,
        group: 'Interaction Details',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    evidence: {
        label: 'Evidence',
        field: 'evidence',
        hidden: false,
        group: 'Interaction Details',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    source_db: {
        label: 'Source DB',
        field: 'source_db',
        hidden: true,
        group: 'Interaction Details',
        facet: true,
        facet_hidden: false,
        search: true,
    },
    pmid: {
        label: 'PubMed',
        field: 'pmid',
        hidden: true,
        group: 'Interaction Details',
        facet: false,
        facet_hidden: true,
        search: false,
    },
    score: {
        label: 'Score',
        field: 'score',
        hidden: true,
        group: 'Interaction Details',
        facet: false,
        facet_hidden: true,
        search: false,
    },
} satisfies DataFieldMap;
